# Generated by Django 5.2.8 on 2025-11-23 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_alter_dropdown_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('is_appoved', models.PositiveSmallIntegerField(choices=[(0, 'applied by patient'), (1, 'Approved by Receptionist'), (2, 'Approved by Doctor')], default=0)),
                ('reason', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.patient')),
            ],
        ),
    ]
