# Generated by Django 5.2.8 on 2025-11-23 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_customuser_role'),
        ('patientPortal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='reason',
            new_name='reason_for_cancel',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='is_appoved',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_status',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.SET_DEFAULT, to='authentication.dropdown'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='reason_to_vist',
            field=models.CharField(default=None, max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor', to='authentication.doctor'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient', to='authentication.patient'),
        ),
    ]
