# Generated by Django 5.2.8 on 2025-11-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='medical_problem',
            field=models.CharField(default=None, max_length=230),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
