# Generated by Django 5.2.8 on 2025-11-23 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0002_appointments_appointment_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='reason',
            new_name='reason_for_cancel',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='medical_problem',
            new_name='reason_to_vist',
        ),
    ]
