# Generated by Django 5.2.8 on 2025-11-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientPortal', '0003_rename_reason_appointments_reason_for_cancel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='is_appoved',
            new_name='is_approved',
        ),
    ]
