# Generated by Django 5.2.8 on 2025-11-23 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_doctor_qualifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('dropdown_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.dropdown')),
                ('hello', models.BooleanField()),
            ],
            bases=('authentication.dropdown',),
        ),
    ]
