# Generated by Django 5.2.8 on 2025-11-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_master'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Master',
        ),
    ]
