# Generated by Django 5.2.8 on 2025-11-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dropdown',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
